# vim: set sts=2 sw=2 ts=2 et ft=ansible:
---

- name: Required packages
  apt: name={{ item }} state=latest
  with_items:
    - zsh
    - python3-pip
    - python-pip
    - git

- name: Required global python packages
  pip: name={{ item }}, executable=pip3
  with_items:
    - virtualenvwrapper
    - colorama

- name: Checkout oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: '/home/{{ my_username }}/.oh-my-zsh'
    force: yes
  become_user: '{{ my_username }}'

# NOTE: Maybe we should create a file in /etc/sudoers.d/USERNAME and put this settings there.
- name: Configure passwordless sudo.
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'

- name: Configure id_rsa (copy from host location).
  copy:
    src: '/home/kaniabi/.ssh/id_rsa'
    dest: '/home/{{ my_username }}/.ssh/id_rsa'
    owner: '{{ my_username }}'
    group: '{{ my_username }}'
    mode: 0600

# NOTE: We checkout dotfiles using GIT protocol so we can push changes later.
# NOTE: This must come AFTER id_rsa is configured.
- name: Checkout dotfiles
  git:
    repo: "git@github.com:{{ my_github_account }}/dotfiles.git"
    dest: '/home/{{ my_username }}/.dotfiles'
    force: yes
    version: master
    accept_hostkey: yes
  become_user: '{{ my_username }}'

- name: Install dotfiles
  shell: '~/.dotfiles/script/bootstrap'
  args:
    creates: '~/.zshrc'
  become_user: '{{ my_username }}'
